# Generated by Django 2.2.4 on 2019-08-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_tb_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='basic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(max_length=4)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
