# Generated by Django 2.2.4 on 2019-08-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_basic'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('salary', models.IntegerField(max_length=20)),
                ('job_title', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='basic',
            name='age',
            field=models.IntegerField(),
        ),
    ]
